vim.g.colors_name = "cppdark"

local hl = vim.api.nvim_set_hl

-- Other
hl(0, "@attribute", { fg = "#51a8b3" })
hl(0, "@attribute.builtin", { fg = "#57a5e5" })
hl(0, "@boolean", { fg = "#c49060" })
hl(0, "@character", { fg = "#c49060" })
hl(0, "@character.special", { fg = "#de5d68" })
hl(0, "@comment", { fg = "#5a5b5e", italic = true })
hl(0, "@comment.documentation", { fg = "#5a5b5e", italic = true })
hl(0, "@comment.error", { fg = "#de5d68", italic = true })
hl(0, "@comment.note", { fg = "#57a5e5", italic = true })
hl(0, "@comment.todo", { fg = "#bb70d2", italic = true })
hl(0, "@comment.warning", { fg = "#dbb671", italic = true })
hl(0, "@conceal", { fg = "#5a5b5e" })
hl(0, "@constant", { fg = "#c49060" })
hl(0, "@constant.builtin", { fg = "#c49060" })
hl(0, "@constant.macro", { fg = "#c49060" })
hl(0, "@constant.macro.c", { fg = "#4fc1ff" })
hl(0, "@constant.macro.cpp", { fg = "#4fc1ff" })
hl(0, "@constructor", { fg = "#dbb671", bold = true })
hl(0, "@diff.delta", { fg = "#57a5e5" })
hl(0, "@diff.minus", { fg = "#de5d68" })
hl(0, "@diff.plus", { fg = "#8fb573" })
hl(0, "@function", { fg = "#57a5e5" })
hl(0, "@function.builtin", { fg = "#51a8b3" })
hl(0, "@function.call", { fg = "#57a5e5" })
hl(0, "@function.macro", { fg = "#c586c0" })
hl(0, "@function.method", { fg = "#57a5e5" })
hl(0, "@function.method.call", { fg = "#57a5e5" })
hl(0, "@keyword", { fg = "#bb70d2" })
hl(0, "@keyword.conditional", { fg = "#bb70d2" })
hl(0, "@keyword.conditional.ternary", { fg = "#bb70d2" })
hl(0, "@keyword.coroutine", { fg = "#bb70d2" })
hl(0, "@keyword.debug", { fg = "#de5d68" })
hl(0, "@keyword.directive", { fg = "#bb70d2" })
hl(0, "@keyword.directive.c", { fg = "#c586c0" })
hl(0, "@keyword.directive.cpp", { fg = "#c586c0" })
hl(0, "@keyword.directive.define", { fg = "#bb70d2" })
hl(0, "@keyword.directive.define.c", { fg = "#c586c0" })
hl(0, "@keyword.directive.define.cpp", { fg = "#c586c0" })
hl(0, "@keyword.exception", { fg = "#bb70d2" })
hl(0, "@keyword.function", { fg = "#bb70d2" })
hl(0, "@keyword.import", { fg = "#bb70d2" })
hl(0, "@keyword.modifier", { fg = "#bb70d2" })
hl(0, "@keyword.operator", { fg = "#bb70d2" })
hl(0, "@keyword.repeat", { fg = "#bb70d2" })
hl(0, "@keyword.return", { fg = "#bb70d2" })
hl(0, "@keyword.type", { fg = "#bb70d2" })
hl(0, "@keyword.type.c", { fg = "#4ec9b0" })
hl(0, "@keyword.type.cpp", { fg = "#4ec9b0" })
hl(0, "@label", { fg = "#de5d68" })
hl(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hl(0, "@lsp.type.builtinType", { fg = "#c49060" })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.comment", { fg = "#5a5b5e", italic = true })
hl(0, "@lsp.type.decorator", { link = "@attribute" })
hl(0, "@lsp.type.enum", { fg = "#dbb671" })
hl(0, "@lsp.type.enumMember", { fg = "#c49060" })
hl(0, "@lsp.type.event", { link = "@type" })
hl(0, "@lsp.type.function", { link = "@function" })
hl(0, "@lsp.type.interface", { fg = "#dbb671" })
hl(0, "@lsp.type.keyword", { fg = "#bb70d2" })
hl(0, "@lsp.type.macro", { fg = "#51a8b3" })
hl(0, "@lsp.type.method", { fg = "#57a5e5" })
hl(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hl(0, "@lsp.type.namespace", { fg = "#dbb671" })
hl(0, "@lsp.type.number", { fg = "#c49060" })
hl(0, "@lsp.type.operator", { link = "@operator" })
hl(0, "@lsp.type.parameter", { fg = "#de5d68" })
hl(0, "@lsp.type.property", { fg = "#51a8b3" })
hl(0, "@lsp.type.regexp", { link = "@string.regexp" })
hl(0, "@lsp.type.string", { link = "@string" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.type", { link = "@type" })
hl(0, "@lsp.type.typeParameter", { fg = "#dbb671" })
hl(0, "@lsp.type.variable", { fg = "#a7aab0" })
hl(0, "@lsp.typemod.function.defaultLibrary", { fg = "#57a5e5" })
hl(0, "@lsp.typemod.method.defaultLibrary", { fg = "#57a5e5" })
hl(0, "@lsp.typemod.operator.injected", { fg = "#a7aab0" })
hl(0, "@lsp.typemod.string.injected", { fg = "#8fb573" })
hl(0, "@lsp.typemod.variable.defaultLibrary", { fg = "#de5d68" })
hl(0, "@lsp.typemod.variable.injected", { fg = "#a7aab0" })
hl(0, "@lsp.typemod.variable.static", { fg = "#c49060" })
hl(0, "@markup", { link = "Special" })
hl(0, "@markup.heading", { fg = "#c49060", bold = true })
hl(0, "@markup.heading.1", { fg = "#de5d68", bold = true })
hl(0, "@markup.heading.1.delimiter.vimdoc", {
	fg = "#000000",
	bg = "#000000",
	sp = "#a7aab0",
	nocombine = true,
})
hl(0, "@markup.heading.2", { fg = "#bb70d2", bold = true })
hl(
	0,
	"@markup.heading.2.delimiter.vimdoc",
	{ fg = "#000000", bg = "#000000", sp = "#a7aab0", underline = true, nocombine = true }
)
hl(0, "@markup.heading.3", { fg = "#c49060", bold = true })
hl(0, "@markup.heading.4", { fg = "#de5d68", bold = true })
hl(0, "@markup.heading.5", { fg = "#bb70d2", bold = true })
hl(0, "@markup.heading.6", { fg = "#c49060", bold = true })
hl(0, "@markup.italic", { fg = "#a7aab0", italic = true })
hl(0, "@markup.link", { fg = "#57a5e5" })
hl(0, "@markup.link.label", { fg = "#51a8b3" })
hl(0, "@markup.link.url", { fg = "#51a8b3", underline = true })
hl(0, "@markup.list", { fg = "#de5d68" })
hl(0, "@markup.list.checked", { fg = "#8fb573", italic = true })
hl(0, "@markup.list.unchecked", { fg = "#de5d68", italic = true })
hl(0, "@markup.math", { fg = "#a7aab0" })
hl(0, "@markup.quote", { fg = "#5a5b5e", italic = true })
hl(0, "@markup.raw", { fg = "#8fb573" })
hl(0, "@markup.raw.block", { fg = "#8fb573" })
hl(0, "@markup.strikethrough", { fg = "#a7aab0", strikethrough = true })
hl(0, "@markup.strong", { fg = "#a7aab0", bold = true })
hl(0, "@markup.underline", { fg = "#a7aab0", underline = true })
hl(0, "@module", { fg = "#dbb671" })
hl(0, "@module.builtin", { fg = "#c49060" })
hl(0, "@none", { fg = "#a7aab0" })
hl(0, "@number", { fg = "#c49060" })
hl(0, "@number.float", { fg = "#c49060" })
hl(0, "@operator", { fg = "#a7aab0" })
hl(0, "@property", { fg = "#51a8b3" })
hl(0, "@punctuation", { link = "Delimiter" })
hl(0, "@punctuation.bracket", { fg = "#818387" })
hl(0, "@punctuation.delimiter", { fg = "#818387" })
hl(0, "@punctuation.special", { fg = "#de5d68" })
hl(0, "@string", { fg = "#8fb573" })
hl(0, "@string.documentation", { fg = "#8fb573" })
hl(0, "@string.escape", { fg = "#de5d68" })
hl(0, "@string.regexp", { fg = "#c49060" })
hl(0, "@string.special", { fg = "#2b5d63" })
hl(0, "@string.special.path", { fg = "#8fb573" })
hl(0, "@string.special.symbol", { fg = "#51a8b3" })
hl(0, "@string.special.url", { fg = "#51a8b3", underline = true })
hl(0, "@tag", { fg = "#bb70d2" })
hl(0, "@tag.attribute", { fg = "#dbb671" })
hl(0, "@tag.builtin", { fg = "#bb70d2" })
hl(0, "@tag.delimiter", { fg = "#bb70d2" })
hl(0, "@type", { fg = "#dbb671" })
hl(0, "@type.builtin", { fg = "#c49060" })
hl(0, "@type.builtin.c", { fg = "#4ec9b0" })
hl(0, "@type.builtin.cpp", { fg = "#4ec9b0" })
hl(0, "@type.definition", { fg = "#dbb671" })
hl(0, "@variable", { fg = "#a7aab0" })
hl(0, "@variable.builtin", { fg = "#de5d68" })
hl(0, "@variable.member", { fg = "#51a8b3" })
hl(0, "@variable.parameter", { fg = "#de5d68" })
hl(0, "@variable.parameter.builtin", { fg = "#c49060" })
hl(0, "ALEErrorSign", { fg = "#de5d68" })
hl(0, "ALEInfoSign", { fg = "#51a8b3" })
hl(0, "ALEWarningSign", { fg = "#dbb671" })

-- Added
hl(0, "Added", { fg = "#8fb573" })

-- Aerial
hl(0, "AerialArrayIcon", { fg = "#dbb671" })
hl(0, "AerialBooleanIcon", { fg = "#c49060" })
hl(0, "AerialClassIcon", { fg = "#dbb671" })
hl(0, "AerialColorIcon", { fg = "#8fb573" })
hl(0, "AerialConstantIcon", { fg = "#c49060" })
hl(0, "AerialConstructorIcon", { fg = "#57a5e5" })
hl(0, "AerialDefaultIcon", { fg = "#bb70d2" })
hl(0, "AerialEnumIcon", { fg = "#bb70d2" })
hl(0, "AerialEnumMemberIcon", { fg = "#dbb671" })
hl(0, "AerialEventIcon", { fg = "#dbb671" })
hl(0, "AerialFieldIcon", { fg = "#bb70d2" })
hl(0, "AerialFileIcon", { fg = "#57a5e5" })
hl(0, "AerialFolderIcon", { fg = "#c49060" })
hl(0, "AerialFunctionIcon", { fg = "#57a5e5" })
hl(0, "AerialInterfaceIcon", { fg = "#8fb573" })
hl(0, "AerialKeyIcon", { fg = "#51a8b3" })
hl(0, "AerialKeywordIcon", { fg = "#51a8b3" })
hl(0, "AerialLine", { fg = "#bb70d2", bg = "#35363b", bold = true })
hl(0, "AerialMethodIcon", { fg = "#57a5e5" })
hl(0, "AerialModuleIcon", { fg = "#c49060" })
hl(0, "AerialNamespaceIcon", { fg = "#de5d68" })
hl(0, "AerialNullIcon", { fg = "#5a5b5e" })
hl(0, "AerialNumberIcon", { fg = "#c49060" })
hl(0, "AerialObjectIcon", { fg = "#de5d68" })
hl(0, "AerialOperatorIcon", { fg = "#de5d68" })
hl(0, "AerialPackageIcon", { fg = "#dbb671" })
hl(0, "AerialPropertyIcon", { fg = "#51a8b3" })
hl(0, "AerialReferenceIcon", { fg = "#c49060" })
hl(0, "AerialSnippetIcon", { fg = "#de5d68" })
hl(0, "AerialStringIcon", { fg = "#8fb573" })
hl(0, "AerialStructIcon", { fg = "#bb70d2" })
hl(0, "AerialTextIcon", { fg = "#818387" })
hl(0, "AerialTypeParameterIcon", { fg = "#de5d68" })
hl(0, "AerialUnitIcon", { fg = "#8fb573" })
hl(0, "AerialValueIcon", { fg = "#c49060" })
hl(0, "AerialVariableIcon", { fg = "#bb70d2" })

-- Blink
hl(0, "BlinkCmpDetail", { fg = "#818387" })
hl(0, "BlinkCmpKind", { fg = "#bb70d2" })
hl(0, "BlinkCmpKindArray", { fg = "#dbb671" })
hl(0, "BlinkCmpKindBoolean", { fg = "#c49060" })
hl(0, "BlinkCmpKindClass", { fg = "#dbb671" })
hl(0, "BlinkCmpKindColor", { fg = "#8fb573" })
hl(0, "BlinkCmpKindConstant", { fg = "#c49060" })
hl(0, "BlinkCmpKindConstructor", { fg = "#57a5e5" })
hl(0, "BlinkCmpKindDefault", { fg = "#bb70d2" })
hl(0, "BlinkCmpKindEnum", { fg = "#bb70d2" })
hl(0, "BlinkCmpKindEnumMember", { fg = "#dbb671" })
hl(0, "BlinkCmpKindEvent", { fg = "#dbb671" })
hl(0, "BlinkCmpKindField", { fg = "#bb70d2" })
hl(0, "BlinkCmpKindFile", { fg = "#57a5e5" })
hl(0, "BlinkCmpKindFolder", { fg = "#c49060" })
hl(0, "BlinkCmpKindFunction", { fg = "#57a5e5" })
hl(0, "BlinkCmpKindInterface", { fg = "#8fb573" })
hl(0, "BlinkCmpKindKey", { fg = "#51a8b3" })
hl(0, "BlinkCmpKindKeyword", { fg = "#51a8b3" })
hl(0, "BlinkCmpKindMethod", { fg = "#57a5e5" })
hl(0, "BlinkCmpKindModule", { fg = "#c49060" })
hl(0, "BlinkCmpKindNamespace", { fg = "#de5d68" })
hl(0, "BlinkCmpKindNull", { fg = "#5a5b5e" })
hl(0, "BlinkCmpKindNumber", { fg = "#c49060" })
hl(0, "BlinkCmpKindObject", { fg = "#de5d68" })
hl(0, "BlinkCmpKindOperator", { fg = "#de5d68" })
hl(0, "BlinkCmpKindPackage", { fg = "#dbb671" })
hl(0, "BlinkCmpKindProperty", { fg = "#51a8b3" })
hl(0, "BlinkCmpKindReference", { fg = "#c49060" })
hl(0, "BlinkCmpKindSnippet", { fg = "#de5d68" })
hl(0, "BlinkCmpKindString", { fg = "#8fb573" })
hl(0, "BlinkCmpKindStruct", { fg = "#bb70d2" })
hl(0, "BlinkCmpKindText", { fg = "#818387" })
hl(0, "BlinkCmpKindTypeParameter", { fg = "#de5d68" })
hl(0, "BlinkCmpKindUnit", { fg = "#8fb573" })
hl(0, "BlinkCmpKindValue", { fg = "#c49060" })
hl(0, "BlinkCmpKindVariable", { fg = "#bb70d2" })
hl(0, "BlinkCmpLabel", { fg = "#a7aab0" })
hl(0, "BlinkCmpLabelDeprecated", { fg = "#818387", strikethrough = true })
hl(0, "BlinkCmpLabelMatch", { fg = "#51a8b3" })

-- Boolean
hl(0, "Boolean", { fg = "#c49060" })

-- Buffer
hl(0, "BufferCurrent", { bold = true })
hl(0, "BufferCurrentMod", { fg = "#c49060", bold = true, italic = true })
hl(0, "BufferCurrentSign", { fg = "#bb70d2" })
hl(0, "BufferInactiveMod", { fg = "#818387", bg = "#2c2d31", italic = true })
hl(0, "BufferVisible", { fg = "#818387", bg = "#000000" })
hl(0, "BufferVisibleIndex", { fg = "#818387", bg = "#000000" })
hl(0, "BufferVisibleMod", { fg = "#dbb671", bg = "#000000", italic = true })
hl(0, "BufferVisibleSign", { fg = "#818387", bg = "#000000" })
hl(0, "BufferVisibleTarget", { fg = "#818387", bg = "#000000" })

-- Changed
hl(0, "Changed", { fg = "#57a5e5" })

-- Character
hl(0, "Character", { fg = "#c49060" })

-- Cmp
hl(0, "CmpItemAbbr", { fg = "#a7aab0" })
hl(0, "CmpItemAbbrDeprecated", { fg = "#818387", strikethrough = true })
hl(0, "CmpItemAbbrMatch", { fg = "#51a8b3" })
hl(0, "CmpItemAbbrMatchFuzzy", { fg = "#51a8b3", underline = true })
hl(0, "CmpItemKind", { fg = "#bb70d2" })
hl(0, "CmpItemKindArray", { fg = "#dbb671" })
hl(0, "CmpItemKindBoolean", { fg = "#c49060" })
hl(0, "CmpItemKindClass", { fg = "#dbb671" })
hl(0, "CmpItemKindColor", { fg = "#8fb573" })
hl(0, "CmpItemKindConstant", { fg = "#c49060" })
hl(0, "CmpItemKindConstructor", { fg = "#57a5e5" })
hl(0, "CmpItemKindDefault", { fg = "#bb70d2" })
hl(0, "CmpItemKindEnum", { fg = "#bb70d2" })
hl(0, "CmpItemKindEnumMember", { fg = "#dbb671" })
hl(0, "CmpItemKindEvent", { fg = "#dbb671" })
hl(0, "CmpItemKindField", { fg = "#bb70d2" })
hl(0, "CmpItemKindFile", { fg = "#57a5e5" })
hl(0, "CmpItemKindFolder", { fg = "#c49060" })
hl(0, "CmpItemKindFunction", { fg = "#57a5e5" })
hl(0, "CmpItemKindInterface", { fg = "#8fb573" })
hl(0, "CmpItemKindKey", { fg = "#51a8b3" })
hl(0, "CmpItemKindKeyword", { fg = "#51a8b3" })
hl(0, "CmpItemKindMethod", { fg = "#57a5e5" })
hl(0, "CmpItemKindModule", { fg = "#c49060" })
hl(0, "CmpItemKindNamespace", { fg = "#de5d68" })
hl(0, "CmpItemKindNull", { fg = "#5a5b5e" })
hl(0, "CmpItemKindNumber", { fg = "#c49060" })
hl(0, "CmpItemKindObject", { fg = "#de5d68" })
hl(0, "CmpItemKindOperator", { fg = "#de5d68" })
hl(0, "CmpItemKindPackage", { fg = "#dbb671" })
hl(0, "CmpItemKindProperty", { fg = "#51a8b3" })
hl(0, "CmpItemKindReference", { fg = "#c49060" })
hl(0, "CmpItemKindSnippet", { fg = "#de5d68" })
hl(0, "CmpItemKindString", { fg = "#8fb573" })
hl(0, "CmpItemKindStruct", { fg = "#bb70d2" })
hl(0, "CmpItemKindText", { fg = "#818387" })
hl(0, "CmpItemKindTypeParameter", { fg = "#de5d68" })
hl(0, "CmpItemKindUnit", { fg = "#8fb573" })
hl(0, "CmpItemKindValue", { fg = "#c49060" })
hl(0, "CmpItemKindVariable", { fg = "#bb70d2" })
hl(0, "CmpItemMenu", { fg = "#818387" })

-- Coc
hl(0, "CocErrorSign", { fg = "#de5d68" })
hl(0, "CocHintSign", { fg = "#bb70d2" })
hl(0, "CocInfoSign", { fg = "#51a8b3" })
hl(0, "CocWarningSign", { fg = "#dbb671" })

-- Color
hl(0, "ColorColumn", { bg = "#2c2d31" })

-- Comment
hl(0, "Comment", { fg = "#5a5b5e", italic = true })

-- Compl
hl(0, "ComplHint", { link = "NonText" })
hl(0, "ComplHintMore", { link = "MoreMsg" })

-- Conceal
hl(0, "Conceal", { fg = "#5a5b5e", bg = "#2c2d31" })

-- Conditional
hl(0, "Conditional", { fg = "#bb70d2" })

-- Constant
hl(0, "Constant", { fg = "#51a8b3" })

-- Cur
hl(0, "CurSearch", { fg = "#000000", bg = "#c49060" })

-- Cursor
hl(0, "Cursor", { reverse = true })
hl(0, "CursorColumn", { bg = "#2c2d31" })
hl(0, "CursorIM", { reverse = true })
hl(0, "CursorLine", { bg = "#2c2d31" })
hl(0, "CursorLineFold", { link = "FoldColumn" })
hl(0, "CursorLineNr", { fg = "#a7aab0" })
hl(0, "CursorLineSign", { link = "SignColumn" })

-- Dashboard
hl(0, "DashboardCenter", { fg = "#51a8b3" })
hl(0, "DashboardFooter", { fg = "#833b3b", italic = true })
hl(0, "DashboardHeader", { fg = "#dbb671" })
hl(0, "DashboardShortCut", { fg = "#57a5e5" })

-- Debug
hl(0, "Debug", { fg = "#dbb671" })

-- Define
hl(0, "Define", { fg = "#bb70d2" })

-- Delimiter
hl(0, "Delimiter", { fg = "#818387" })

-- Diagnostic
hl(0, "DiagnosticDeprecated", { fg = "#c49060", strikethrough = true })
hl(0, "DiagnosticError", { fg = "#de5d68" })
hl(0, "DiagnosticFloatingError", { link = "DiagnosticError" })
hl(0, "DiagnosticFloatingHint", { link = "DiagnosticHint" })
hl(0, "DiagnosticFloatingInfo", { link = "DiagnosticInfo" })
hl(0, "DiagnosticFloatingOk", { link = "DiagnosticOk" })
hl(0, "DiagnosticFloatingWarn", { link = "DiagnosticWarn" })
hl(0, "DiagnosticHint", { fg = "#bb70d2" })
hl(0, "DiagnosticInfo", { fg = "#51a8b3" })
hl(0, "DiagnosticOk", { fg = "#8fb573" })
hl(0, "DiagnosticSignError", { link = "DiagnosticError" })
hl(0, "DiagnosticSignHint", { link = "DiagnosticHint" })
hl(0, "DiagnosticSignInfo", { link = "DiagnosticInfo" })
hl(0, "DiagnosticSignOk", { link = "DiagnosticOk" })
hl(0, "DiagnosticSignWarn", { link = "DiagnosticWarn" })
hl(0, "DiagnosticUnderlineDeprecated", { sp = "#c49060", strikethrough = true })
hl(0, "DiagnosticUnderlineError", { sp = "#de5d68", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#bb70d2", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#57a5e5", undercurl = true })
hl(0, "DiagnosticUnderlineOk", { sp = "#8fb573", undercurl = true })
hl(0, "DiagnosticUnderlineUnnecessary", { sp = "#5a5b5e", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#dbb671", undercurl = true })
hl(0, "DiagnosticUnnecessary", { fg = "#5a5b5e" })
hl(0, "DiagnosticVirtualLinesError", { link = "DiagnosticError" })
hl(0, "DiagnosticVirtualLinesHint", { link = "DiagnosticHint" })
hl(0, "DiagnosticVirtualLinesInfo", { link = "DiagnosticInfo" })
hl(0, "DiagnosticVirtualLinesOk", { link = "DiagnosticOk" })
hl(0, "DiagnosticVirtualLinesWarn", { link = "DiagnosticWarn" })
hl(0, "DiagnosticVirtualTextDeprecated", { fg = "#c49060", bg = "#140e0a", strikethrough = true })
hl(0, "DiagnosticVirtualTextError", { fg = "#833b3b", bg = "#0d0606" })
hl(0, "DiagnosticVirtualTextHint", { fg = "#79428a", bg = "#0c070e" })
hl(0, "DiagnosticVirtualTextInfo", { fg = "#2b5d63", bg = "#04090a" })
hl(0, "DiagnosticVirtualTextOk", { fg = "#8fb573", bg = "#0e120c" })
hl(0, "DiagnosticVirtualTextUnnecessary", { fg = "#5a5b5e", bg = "#090909" })
hl(0, "DiagnosticVirtualTextWarn", { fg = "#7c5c20", bg = "#0c0903" })
hl(0, "DiagnosticWarn", { fg = "#dbb671" })

-- Diff
hl(0, "DiffAdd", { bg = "#282b26" })
hl(0, "DiffAdded", { fg = "#8fb573" })
hl(0, "DiffChange", { bg = "#1a2a37" })
hl(0, "DiffChanged", { fg = "#57a5e5" })
hl(0, "DiffDelete", { bg = "#2a2626" })
hl(0, "DiffDeleted", { fg = "#de5d68" })
hl(0, "DiffFile", { fg = "#51a8b3" })
hl(0, "DiffIndexLine", { fg = "#5a5b5e" })
hl(0, "DiffRemoved", { fg = "#de5d68" })
hl(0, "DiffText", { bg = "#2c485f" })
hl(0, "DiffTextAdd", { link = "DiffText" })

-- Diffview
hl(0, "DiffviewCursorLine", { bg = "#2c2d31" })
hl(0, "DiffviewEndOfBuffer", { fg = "#000000", bg = "#000000" })
hl(0, "DiffviewFilePanelCounter", { fg = "#bb70d2", bold = true })
hl(0, "DiffviewFilePanelDeletions", { fg = "#de5d68" })
hl(0, "DiffviewFilePanelFileName", { fg = "#a7aab0" })
hl(0, "DiffviewFilePanelInsertions", { fg = "#8fb573" })
hl(0, "DiffviewFilePanelPath", { fg = "#5a5b5e" })
hl(0, "DiffviewFilePanelRootPath", { fg = "#5a5b5e" })
hl(0, "DiffviewFilePanelTitle", { fg = "#57a5e5", bold = true })
hl(0, "DiffviewNormal", { fg = "#a7aab0", bg = "#000000" })
hl(0, "DiffviewSignColumn", { fg = "#a7aab0", bg = "#000000" })
hl(0, "DiffviewStatusAdded", { fg = "#8fb573" })
hl(0, "DiffviewStatusBroken", { fg = "#de5d68" })
hl(0, "DiffviewStatusCopied", { fg = "#57a5e5" })
hl(0, "DiffviewStatusDeleted", { fg = "#de5d68" })
hl(0, "DiffviewStatusLine", { fg = "#a7aab0", bg = "#35363b" })
hl(0, "DiffviewStatusLineNC", { fg = "#5a5b5e", bg = "#2c2d31" })
hl(0, "DiffviewStatusModified", { fg = "#57a5e5" })
hl(0, "DiffviewStatusRenamed", { fg = "#57a5e5" })
hl(0, "DiffviewStatusTypeChange", { fg = "#57a5e5" })
hl(0, "DiffviewStatusUnknown", { fg = "#de5d68" })
hl(0, "DiffviewStatusUnmerged", { fg = "#57a5e5" })
hl(0, "DiffviewStatusUntracked", { fg = "#57a5e5" })

-- Directory
hl(0, "Directory", { fg = "#57a5e5" })

-- Drop
hl(0, "DropBarIconKind", { fg = "#dbb671" })
hl(0, "DropBarKind", { fg = "#a7aab0" })
hl(0, "DropBarKindArray", { fg = "#dbb671" })
hl(0, "DropBarKindBoolean", { fg = "#c49060" })
hl(0, "DropBarKindClass", { fg = "#dbb671" })
hl(0, "DropBarKindColor", { fg = "#8fb573" })
hl(0, "DropBarKindConstant", { fg = "#c49060" })
hl(0, "DropBarKindConstructor", { fg = "#57a5e5" })
hl(0, "DropBarKindDefault", { fg = "#bb70d2" })
hl(0, "DropBarKindEnum", { fg = "#bb70d2" })
hl(0, "DropBarKindEnumMember", { fg = "#dbb671" })
hl(0, "DropBarKindEvent", { fg = "#dbb671" })
hl(0, "DropBarKindField", { fg = "#bb70d2" })
hl(0, "DropBarKindFile", { fg = "#57a5e5" })
hl(0, "DropBarKindFolder", { fg = "#c49060" })
hl(0, "DropBarKindFunction", { fg = "#57a5e5" })
hl(0, "DropBarKindInterface", { fg = "#8fb573" })
hl(0, "DropBarKindKey", { fg = "#51a8b3" })
hl(0, "DropBarKindKeyword", { fg = "#51a8b3" })
hl(0, "DropBarKindMethod", { fg = "#57a5e5" })
hl(0, "DropBarKindModule", { fg = "#c49060" })
hl(0, "DropBarKindNamespace", { fg = "#de5d68" })
hl(0, "DropBarKindNull", { fg = "#5a5b5e" })
hl(0, "DropBarKindNumber", { fg = "#c49060" })
hl(0, "DropBarKindObject", { fg = "#de5d68" })
hl(0, "DropBarKindOperator", { fg = "#de5d68" })
hl(0, "DropBarKindPackage", { fg = "#dbb671" })
hl(0, "DropBarKindProperty", { fg = "#51a8b3" })
hl(0, "DropBarKindReference", { fg = "#c49060" })
hl(0, "DropBarKindSnippet", { fg = "#de5d68" })
hl(0, "DropBarKindString", { fg = "#8fb573" })
hl(0, "DropBarKindStruct", { fg = "#bb70d2" })
hl(0, "DropBarKindText", { fg = "#818387" })
hl(0, "DropBarKindTypeParameter", { fg = "#de5d68" })
hl(0, "DropBarKindUnit", { fg = "#8fb573" })
hl(0, "DropBarKindValue", { fg = "#c49060" })
hl(0, "DropBarKindVariable", { fg = "#bb70d2" })
hl(0, "DropBarMenuHoverIcon", { reverse = true })
hl(0, "DropBarSeparator", { fg = "#5a5b5e" })
hl(0, "DropBarWinBar", { fg = "#a7aab0", bg = "#000000" })

-- End
hl(0, "EndOfBuffer", { fg = "#000000", bg = "#000000" })

-- Error
hl(0, "Error", { fg = "#bb70d2" })
hl(0, "ErrorMsg", { fg = "#de5d68", bold = true })

-- Exception
hl(0, "Exception", { fg = "#bb70d2" })

-- Float
hl(0, "Float", { fg = "#c49060" })
hl(0, "FloatBorder", { fg = "#5a5b5e", bg = "#2c2d31" })
hl(0, "FloatFooter", { link = "FloatTitle" })
hl(0, "FloatShadow", { bg = "#4f5258" })
hl(0, "FloatShadowThrough", { bg = "#4f5258" })
hl(0, "FloatTitle", { link = "Title" })

-- Focused
hl(0, "FocusedSymbol", { fg = "#bb70d2", bg = "#35363b", bold = true })

-- Fold
hl(0, "FoldColumn", { fg = "#a7aab0", bg = "#2c2d31" })

-- Folded
hl(0, "Folded", { fg = "#a7aab0", bg = "#2c2d31" })

-- Function
hl(0, "Function", { fg = "#57a5e5" })

-- Git
hl(0, "GitConflictAncestor", { bg = "#1c1120" })
hl(0, "GitConflictAncestorLabel", { bg = "#2f1c35", bold = true })
hl(0, "GitConflictCurrent", { bg = "#151b11" })
hl(0, "GitConflictCurrentLabel", { bg = "#242d1d", bold = true })
hl(0, "GitConflictIncoming", { bg = "#0d1922" })
hl(0, "GitConflictIncomingLabel", { bg = "#162939", bold = true })
hl(0, "GitGutterAdd", { fg = "#8fb573" })
hl(0, "GitGutterChange", { fg = "#57a5e5" })
hl(0, "GitGutterDelete", { fg = "#de5d68" })
hl(0, "GitSignsAdd", { fg = "#8fb573" })
hl(0, "GitSignsAddLn", { fg = "#8fb573" })
hl(0, "GitSignsAddNr", { fg = "#8fb573" })
hl(0, "GitSignsChange", { fg = "#57a5e5" })
hl(0, "GitSignsChangeLn", { fg = "#57a5e5" })
hl(0, "GitSignsChangeNr", { fg = "#57a5e5" })
hl(0, "GitSignsDelete", { fg = "#de5d68" })
hl(0, "GitSignsDeleteLn", { fg = "#de5d68" })
hl(0, "GitSignsDeleteNr", { fg = "#de5d68" })

-- Hop
hl(0, "HopNextKey", { fg = "#de5d68", bold = true })
hl(0, "HopNextKey1", { fg = "#51a8b3", bold = true })
hl(0, "HopNextKey2", { fg = "#3d73a0" })
hl(0, "HopUnmatched", { fg = "#5a5b5e" })

-- Ibl
hl(0, "IblIndent", { fg = "#414141", nocombine = true })
hl(0, "IblScope", { fg = "#414141", nocombine = true })
hl(0, "IblWhitespace", { fg = "#2c2d31", nocombine = true })

-- Identifier
hl(0, "Identifier", { fg = "#de5d68" })

-- Ignore
hl(0, "Ignore", { link = "Normal" })

-- Illuminated
hl(0, "IlluminatedWordRead", { bg = "#35363b", bold = true })
hl(0, "IlluminatedWordText", { bg = "#35363b", bold = true })
hl(0, "IlluminatedWordWrite", { bg = "#35363b", bold = true })

-- Inc
hl(0, "IncSearch", { fg = "#000000", bg = "#c49060" })

-- Include
hl(0, "Include", { fg = "#bb70d2" })

-- Indent
hl(0, "IndentBlanklineChar", { fg = "#2c2d31", nocombine = true })
hl(0, "IndentBlanklineContextChar", { fg = "#5a5b5e", nocombine = true })
hl(0, "IndentBlanklineContextSpaceChar", { nocombine = true })
hl(0, "IndentBlanklineContextStart", { sp = "#5a5b5e", underline = true })
hl(0, "IndentBlanklineIndent1", { fg = "#57a5e5" })
hl(0, "IndentBlanklineIndent2", { fg = "#8fb573" })
hl(0, "IndentBlanklineIndent3", { fg = "#51a8b3" })
hl(0, "IndentBlanklineIndent4", { fg = "#818387" })
hl(0, "IndentBlanklineIndent5", { fg = "#bb70d2" })
hl(0, "IndentBlanklineIndent6", { fg = "#de5d68" })
hl(0, "IndentLine", { fg = "#35363b" })
hl(0, "IndentLineCurrent", { fg = "#5a5b5e" })

-- Keyword
hl(0, "Keyword", { fg = "#bb70d2" })

-- Label
hl(0, "Label", { fg = "#bb70d2" })

-- Line
hl(0, "LineNr", { fg = "#5a5b5e" })
hl(0, "LineNrAbove", { link = "LineNr" })
hl(0, "LineNrBelow", { link = "LineNr" })

-- Lsp
hl(0, "LspCodeLens", { fg = "#5a5b5e", italic = true })
hl(0, "LspCodeLensSeparator", { fg = "#5a5b5e" })
hl(0, "LspCxxHlGroupEnumConstant", { fg = "#c49060" })
hl(0, "LspCxxHlGroupMemberVariable", { fg = "#c49060" })
hl(0, "LspCxxHlGroupNamespace", { fg = "#57a5e5" })
hl(0, "LspCxxHlSkippedRegion", { fg = "#5a5b5e" })
hl(0, "LspCxxHlSkippedRegionBeginEnd", { fg = "#de5d68" })
hl(0, "LspDiagnosticsDefaultError", { fg = "#de5d68" })
hl(0, "LspDiagnosticsDefaultHint", { fg = "#bb70d2" })
hl(0, "LspDiagnosticsDefaultInformation", { fg = "#51a8b3" })
hl(0, "LspDiagnosticsDefaultWarning", { fg = "#dbb671" })
hl(0, "LspDiagnosticsUnderlineError", { sp = "#de5d68", undercurl = true })
hl(0, "LspDiagnosticsUnderlineHint", { sp = "#bb70d2", undercurl = true })
hl(0, "LspDiagnosticsUnderlineInformation", { sp = "#57a5e5", undercurl = true })
hl(0, "LspDiagnosticsUnderlineWarning", { sp = "#dbb671", undercurl = true })
hl(0, "LspDiagnosticsVirtualTextError", { fg = "#833b3b", bg = "#0d0606" })
hl(0, "LspDiagnosticsVirtualTextHint", { fg = "#79428a", bg = "#0c070e" })
hl(0, "LspDiagnosticsVirtualTextInformation", { fg = "#2b5d63", bg = "#04090a" })
hl(0, "LspDiagnosticsVirtualTextWarning", { fg = "#7c5c20", bg = "#0c0903" })
hl(0, "LspInlayHint", { link = "NonText" })
hl(0, "LspReferenceRead", { bg = "#35363b" })
hl(0, "LspReferenceTarget", { link = "LspReferenceText" })
hl(0, "LspReferenceText", { bg = "#35363b" })
hl(0, "LspReferenceWrite", { bg = "#35363b" })
hl(0, "LspSignatureActiveParameter", { link = "Visual" })

-- Macro
hl(0, "Macro", { fg = "#de5d68" })

-- Match
hl(0, "MatchParen", { bg = "#37383d" })

-- Mini
hl(0, "MiniAnimateCursor", { reverse = true, nocombine = true })
hl(0, "MiniAnimateNormalFloat", { fg = "#a7aab0", bg = "#2c2d31" })
hl(0, "MiniClueBorder", { fg = "#5a5b5e", bg = "#2c2d31" })
hl(0, "MiniClueDescGroup", { fg = "#dbb671" })
hl(0, "MiniClueDescSingle", { fg = "#a7aab0", bg = "#2c2d31" })
hl(0, "MiniClueNextKey", { fg = "#bb70d2" })
hl(0, "MiniClueNextKeyWithPostkeys", { fg = "#de5d68" })
hl(0, "MiniClueSeparator", { fg = "#51a8b3" })
hl(0, "MiniClueTitle", { fg = "#51a8b3" })
hl(0, "MiniCompletionActiveParameter", { underline = true })
hl(0, "MiniCursorword", { underline = true })
hl(0, "MiniCursorwordCurrent", { underline = true })
hl(0, "MiniDepsChangeAdded", { fg = "#8fb573" })
hl(0, "MiniDepsChangeRemoved", { fg = "#de5d68" })
hl(0, "MiniDepsHint", { fg = "#bb70d2" })
hl(0, "MiniDepsInfo", { fg = "#51a8b3" })
hl(0, "MiniDepsMsgBreaking", { fg = "#dbb671" })
hl(0, "MiniDepsPlaceholder", { fg = "#5a5b5e", italic = true })
hl(0, "MiniDepsTitle", { fg = "#51a8b3" })
hl(0, "MiniDepsTitleError", { bg = "#2a2626" })
hl(0, "MiniDepsTitleSame", { bg = "#2c485f" })
hl(0, "MiniDepsTitleUpdate", { bg = "#282b26" })
hl(0, "MiniDiffOverAdd", { bg = "#282b26" })
hl(0, "MiniDiffOverChange", { bg = "#2c485f" })
hl(0, "MiniDiffOverContext", { bg = "#1a2a37" })
hl(0, "MiniDiffOverDelete", { bg = "#2a2626" })
hl(0, "MiniDiffSignAdd", { fg = "#8fb573" })
hl(0, "MiniDiffSignChange", { fg = "#57a5e5" })
hl(0, "MiniDiffSignDelete", { fg = "#de5d68" })
hl(0, "MiniFilesBorder", { fg = "#5a5b5e", bg = "#2c2d31" })
hl(0, "MiniFilesBorderModified", { fg = "#dbb671" })
hl(0, "MiniFilesCursorLine", { bg = "#35363b" })
hl(0, "MiniFilesDirectory", { fg = "#57a5e5" })
hl(0, "MiniFilesFile", { fg = "#a7aab0" })
hl(0, "MiniFilesNormal", { fg = "#a7aab0", bg = "#2c2d31" })
hl(0, "MiniFilesTitle", { fg = "#51a8b3" })
hl(0, "MiniFilesTitleFocused", { fg = "#51a8b3", bold = true })
hl(0, "MiniHipatternsFixme", { fg = "#000000", bg = "#de5d68", bold = true })
hl(0, "MiniHipatternsHack", { fg = "#000000", bg = "#dbb671", bold = true })
hl(0, "MiniHipatternsNote", { fg = "#000000", bg = "#51a8b3", bold = true })
hl(0, "MiniHipatternsTodo", { fg = "#000000", bg = "#bb70d2", bold = true })
hl(0, "MiniIconsAzure", { fg = "#68aee8" })
hl(0, "MiniIconsBlue", { fg = "#57a5e5" })
hl(0, "MiniIconsCyan", { fg = "#51a8b3" })
hl(0, "MiniIconsGreen", { fg = "#8fb573" })
hl(0, "MiniIconsGrey", { fg = "#a7aab0" })
hl(0, "MiniIconsOrange", { fg = "#c49060" })
hl(0, "MiniIconsPurple", { fg = "#bb70d2" })
hl(0, "MiniIconsRed", { fg = "#de5d68" })
hl(0, "MiniIconsYellow", { fg = "#dbb671" })
hl(0, "MiniIndentscopePrefix", { nocombine = true })
hl(0, "MiniIndentscopeSymbol", { fg = "#5a5b5e" })
hl(0, "MiniJump", { fg = "#bb70d2", sp = "#bb70d2", underline = true })
hl(0, "MiniJump2dDim", { fg = "#5a5b5e", nocombine = true })
hl(0, "MiniJump2dSpot", { fg = "#de5d68", bold = true, nocombine = true })
hl(0, "MiniJump2dSpotAhead", { fg = "#51a8b3", bg = "#000000", nocombine = true })
hl(0, "MiniJump2dSpotUnique", { fg = "#dbb671", bold = true, nocombine = true })
hl(0, "MiniMapNormal", { fg = "#a7aab0", bg = "#2c2d31" })
hl(0, "MiniMapSymbolCount", { fg = "#de5d68" })
hl(0, "MiniMapSymbolLine", { fg = "#51a8b3" })
hl(0, "MiniMapSymbolView", { fg = "#818387" })
hl(0, "MiniNotifyBorder", { fg = "#5a5b5e", bg = "#2c2d31" })
hl(0, "MiniNotifyNormal", { fg = "#a7aab0", bg = "#2c2d31" })
hl(0, "MiniNotifyTitle", { fg = "#51a8b3" })
hl(0, "MiniOperatorsExchangeFrom", { fg = "#000000", bg = "#c49060" })
hl(0, "MiniPickBorder", { fg = "#5a5b5e", bg = "#2c2d31" })
hl(0, "MiniPickBorderBusy", { fg = "#dbb671" })
hl(0, "MiniPickBorderText", { fg = "#51a8b3", bold = true })
hl(0, "MiniPickHeader", { fg = "#bb70d2" })
hl(0, "MiniPickIconDirectory", { fg = "#57a5e5" })
hl(0, "MiniPickIconFile", { fg = "#a7aab0", bg = "#2c2d31" })
hl(0, "MiniPickMatchCurrent", { bg = "#35363b" })
hl(0, "MiniPickMatchMarked", { bg = "#2c485f" })
hl(0, "MiniPickMatchRanges", { fg = "#bb70d2" })
hl(0, "MiniPickNormal", { fg = "#a7aab0", bg = "#2c2d31" })
hl(0, "MiniPickPreviewLine", { bg = "#35363b" })
hl(0, "MiniPickPreviewRegion", { fg = "#000000", bg = "#c49060" })
hl(0, "MiniPickPrompt", { fg = "#51a8b3" })
hl(0, "MiniStarterCurrent", { nocombine = true })
hl(0, "MiniStarterFooter", { fg = "#833b3b", italic = true })
hl(0, "MiniStarterHeader", { fg = "#dbb671" })
hl(0, "MiniStarterInactive", { fg = "#5a5b5e", italic = true })
hl(0, "MiniStarterItem", { fg = "#a7aab0", bg = "#000000" })
hl(0, "MiniStarterItemBullet", { fg = "#5a5b5e" })
hl(0, "MiniStarterItemPrefix", { fg = "#dbb671" })
hl(0, "MiniStarterQuery", { fg = "#51a8b3" })
hl(0, "MiniStarterSection", { fg = "#818387" })
hl(0, "MiniStatuslineDevinfo", { fg = "#a7aab0", bg = "#35363b" })
hl(0, "MiniStatuslineFileinfo", { fg = "#a7aab0", bg = "#35363b" })
hl(0, "MiniStatuslineFilename", { fg = "#5a5b5e", bg = "#2c2d31" })
hl(0, "MiniStatuslineInactive", { fg = "#5a5b5e", bg = "#2c2d31" })
hl(0, "MiniStatuslineModeCommand", { fg = "#000000", bg = "#dbb671", bold = true })
hl(0, "MiniStatuslineModeInsert", { fg = "#000000", bg = "#57a5e5", bold = true })
hl(0, "MiniStatuslineModeNormal", { fg = "#000000", bg = "#8fb573", bold = true })
hl(0, "MiniStatuslineModeOther", { fg = "#000000", bg = "#51a8b3", bold = true })
hl(0, "MiniStatuslineModeReplace", { fg = "#000000", bg = "#de5d68", bold = true })
hl(0, "MiniStatuslineModeVisual", { fg = "#000000", bg = "#bb70d2", bold = true })
hl(0, "MiniSurround", { fg = "#000000", bg = "#c49060" })
hl(0, "MiniTablineCurrent", { bold = true })
hl(0, "MiniTablineFill", { fg = "#5a5b5e", bg = "#2c2d31" })
hl(0, "MiniTablineHidden", { fg = "#a7aab0", bg = "#2c2d31" })
hl(0, "MiniTablineModifiedCurrent", { fg = "#c49060", bold = true, italic = true })
hl(0, "MiniTablineModifiedHidden", { fg = "#818387", bg = "#2c2d31", italic = true })
hl(0, "MiniTablineModifiedVisible", { fg = "#dbb671", bg = "#000000", italic = true })
hl(0, "MiniTablineTabpagesection", { fg = "#000000", bg = "#e2c792" })
hl(0, "MiniTablineVisible", { fg = "#818387", bg = "#000000" })
hl(0, "MiniTestEmphasis", { bold = true })
hl(0, "MiniTestFail", { fg = "#de5d68", bold = true })
hl(0, "MiniTestPass", { fg = "#8fb573", bold = true })
hl(0, "MiniTrailspace", { bg = "#de5d68" })

-- Mode
hl(0, "ModeMsg", { fg = "#b3f6c0" })

-- More
hl(0, "MoreMsg", { fg = "#57a5e5", bold = true })

-- Msg
hl(0, "MsgSeparator", { link = "StatusLine" })

-- Navic
hl(0, "NavicIconsArray", { fg = "#dbb671" })
hl(0, "NavicIconsBoolean", { fg = "#c49060" })
hl(0, "NavicIconsClass", { fg = "#dbb671" })
hl(0, "NavicIconsColor", { fg = "#8fb573" })
hl(0, "NavicIconsConstant", { fg = "#c49060" })
hl(0, "NavicIconsConstructor", { fg = "#57a5e5" })
hl(0, "NavicIconsDefault", { fg = "#bb70d2" })
hl(0, "NavicIconsEnum", { fg = "#bb70d2" })
hl(0, "NavicIconsEnumMember", { fg = "#dbb671" })
hl(0, "NavicIconsEvent", { fg = "#dbb671" })
hl(0, "NavicIconsField", { fg = "#bb70d2" })
hl(0, "NavicIconsFile", { fg = "#57a5e5" })
hl(0, "NavicIconsFolder", { fg = "#c49060" })
hl(0, "NavicIconsFunction", { fg = "#57a5e5" })
hl(0, "NavicIconsInterface", { fg = "#8fb573" })
hl(0, "NavicIconsKey", { fg = "#51a8b3" })
hl(0, "NavicIconsKeyword", { fg = "#51a8b3" })
hl(0, "NavicIconsMethod", { fg = "#57a5e5" })
hl(0, "NavicIconsModule", { fg = "#c49060" })
hl(0, "NavicIconsNamespace", { fg = "#de5d68" })
hl(0, "NavicIconsNull", { fg = "#5a5b5e" })
hl(0, "NavicIconsNumber", { fg = "#c49060" })
hl(0, "NavicIconsObject", { fg = "#de5d68" })
hl(0, "NavicIconsOperator", { fg = "#de5d68" })
hl(0, "NavicIconsPackage", { fg = "#dbb671" })
hl(0, "NavicIconsProperty", { fg = "#51a8b3" })
hl(0, "NavicIconsReference", { fg = "#c49060" })
hl(0, "NavicIconsSnippet", { fg = "#de5d68" })
hl(0, "NavicIconsString", { fg = "#8fb573" })
hl(0, "NavicIconsStruct", { fg = "#bb70d2" })
hl(0, "NavicIconsText", { fg = "#818387" })
hl(0, "NavicIconsTypeParameter", { fg = "#de5d68" })
hl(0, "NavicIconsUnit", { fg = "#8fb573" })
hl(0, "NavicIconsValue", { fg = "#c49060" })
hl(0, "NavicIconsVariable", { fg = "#bb70d2" })
hl(0, "NavicSeparator", { fg = "#818387" })
hl(0, "NavicText", { fg = "#a7aab0" })

-- Neo
hl(0, "NeoTreeEndOfBuffer", { fg = "#1b1c1e", bg = "#1b1c1e" })
hl(0, "NeoTreeGitAdded", { fg = "#8fb573" })
hl(0, "NeoTreeGitConflict", { fg = "#de5d68", bold = true, italic = true })
hl(0, "NeoTreeGitDeleted", { fg = "#de5d68" })
hl(0, "NeoTreeGitModified", { fg = "#dbb671" })
hl(0, "NeoTreeGitUntracked", { fg = "#de5d68", italic = true })
hl(0, "NeoTreeIndentMarker", { fg = "#5a5b5e" })
hl(0, "NeoTreeNormal", { fg = "#a7aab0", bg = "#1b1c1e" })
hl(0, "NeoTreeNormalNC", { fg = "#a7aab0", bg = "#1b1c1e" })
hl(0, "NeoTreeRootName", { fg = "#c49060", bold = true })
hl(0, "NeoTreeSymbolicLinkTarget", { fg = "#bb70d2" })
hl(0, "NeoTreeVertSplit", { fg = "#2c2d31", bg = "#2c2d31" })
hl(0, "NeoTreeWinSeparator", { fg = "#2c2d31", bg = "#2c2d31" })

-- Neotest
hl(0, "NeotestAdapterName", { fg = "#bb70d2", bold = true })
hl(0, "NeotestDir", { fg = "#51a8b3" })
hl(0, "NeotestExpandMarker", { fg = "#5a5b5e" })
hl(0, "NeotestFailed", { fg = "#de5d68" })
hl(0, "NeotestFile", { fg = "#51a8b3" })
hl(0, "NeotestFocused", { bold = true, italic = true })
hl(0, "NeotestIndent", { fg = "#5a5b5e" })
hl(0, "NeotestMarked", { fg = "#c49060", bold = true })
hl(0, "NeotestNamespace", { fg = "#57a5e5" })
hl(0, "NeotestPassed", { fg = "#8fb573" })
hl(0, "NeotestRunning", { fg = "#dbb671" })
hl(0, "NeotestSkipped", { fg = "#818387" })
hl(0, "NeotestTarget", { fg = "#bb70d2" })
hl(0, "NeotestTest", { fg = "#a7aab0" })
hl(0, "NeotestUnknown", { fg = "#818387" })
hl(0, "NeotestWinSelect", { fg = "#51a8b3", bold = true })

-- Non
hl(0, "NonText", { fg = "#5a5b5e" })

-- Normal
hl(0, "Normal", { fg = "#a7aab0", bg = "#000000" })
hl(0, "NormalFloat", { fg = "#a7aab0", bg = "#2c2d31" })

-- Number
hl(0, "Number", { fg = "#c49060" })

-- Nvim
hl(0, "NvimAnd", { link = "NvimBinaryOperator" })
hl(0, "NvimArrow", { link = "Delimiter" })
hl(0, "NvimAssignment", { link = "Operator" })
hl(0, "NvimAssignmentWithAddition", { link = "NvimAugmentedAssignment" })
hl(0, "NvimAssignmentWithConcatenation", { link = "NvimAugmentedAssignment" })
hl(0, "NvimAssignmentWithSubtraction", { link = "NvimAugmentedAssignment" })
hl(0, "NvimAugmentedAssignment", { link = "NvimAssignment" })
hl(0, "NvimBinaryMinus", { link = "NvimBinaryOperator" })
hl(0, "NvimBinaryOperator", { link = "NvimOperator" })
hl(0, "NvimBinaryPlus", { link = "NvimBinaryOperator" })
hl(0, "NvimCallingParenthesis", { link = "NvimParenthesis" })
hl(0, "NvimColon", { link = "Delimiter" })
hl(0, "NvimComma", { link = "Delimiter" })
hl(0, "NvimComparison", { link = "NvimBinaryOperator" })
hl(0, "NvimComparisonModifier", { link = "NvimComparison" })
hl(0, "NvimConcat", { link = "NvimBinaryOperator" })
hl(0, "NvimConcatOrSubscript", { link = "NvimConcat" })
hl(0, "NvimContainer", { link = "NvimParenthesis" })
hl(0, "NvimCurly", { link = "NvimSubscript" })
hl(0, "NvimDict", { link = "NvimContainer" })
hl(0, "NvimDivision", { link = "NvimBinaryOperator" })
hl(0, "NvimDoubleQuote", { link = "NvimStringQuote" })
hl(0, "NvimDoubleQuotedBody", { link = "NvimStringBody" })
hl(0, "NvimDoubleQuotedEscape", { link = "NvimStringSpecial" })
hl(0, "NvimDoubleQuotedUnknownEscape", { link = "NvimInvalidValue" })
hl(0, "NvimEnvironmentName", { link = "NvimIdentifier" })
hl(0, "NvimEnvironmentSigil", { link = "NvimOptionSigil" })
hl(0, "NvimFigureBrace", { link = "NvimInternalError" })
hl(0, "NvimFloat", { link = "NvimNumber" })
hl(0, "NvimIdentifier", { link = "Identifier" })
hl(0, "NvimIdentifierKey", { link = "NvimIdentifier" })
hl(0, "NvimIdentifierName", { link = "NvimIdentifier" })
hl(0, "NvimIdentifierScope", { link = "NvimIdentifier" })
hl(0, "NvimIdentifierScopeDelimiter", { link = "NvimIdentifier" })
hl(0, "NvimInternalError", { fg = "#ff0000", bg = "#ff0000" })
hl(0, "NvimInvalid", { link = "Error" })
hl(0, "NvimInvalidAnd", { link = "NvimInvalidBinaryOperator" })
hl(0, "NvimInvalidArrow", { link = "NvimInvalidDelimiter" })
hl(0, "NvimInvalidAssignment", { link = "NvimInvalid" })
hl(0, "NvimInvalidAssignmentWithAddition", { link = "NvimInvalidAugmentedAssignment" })
hl(0, "NvimInvalidAssignmentWithConcatenation", { link = "NvimInvalidAugmentedAssignment" })
hl(0, "NvimInvalidAssignmentWithSubtraction", { link = "NvimInvalidAugmentedAssignment" })
hl(0, "NvimInvalidAugmentedAssignment", { link = "NvimInvalidAssignment" })
hl(0, "NvimInvalidBinaryMinus", { link = "NvimInvalidBinaryOperator" })
hl(0, "NvimInvalidBinaryOperator", { link = "NvimInvalidOperator" })
hl(0, "NvimInvalidBinaryPlus", { link = "NvimInvalidBinaryOperator" })
hl(0, "NvimInvalidCallingParenthesis", { link = "NvimInvalidParenthesis" })
hl(0, "NvimInvalidColon", { link = "NvimInvalidDelimiter" })
hl(0, "NvimInvalidComma", { link = "NvimInvalidDelimiter" })
hl(0, "NvimInvalidComparison", { link = "NvimInvalidBinaryOperator" })
hl(0, "NvimInvalidComparisonModifier", { link = "NvimInvalidComparison" })
hl(0, "NvimInvalidConcat", { link = "NvimInvalidBinaryOperator" })
hl(0, "NvimInvalidConcatOrSubscript", { link = "NvimInvalidConcat" })
hl(0, "NvimInvalidContainer", { link = "NvimInvalidParenthesis" })
hl(0, "NvimInvalidCurly", { link = "NvimInvalidSubscript" })
hl(0, "NvimInvalidDelimiter", { link = "NvimInvalid" })
hl(0, "NvimInvalidDict", { link = "NvimInvalidContainer" })
hl(0, "NvimInvalidDivision", { link = "NvimInvalidBinaryOperator" })
hl(0, "NvimInvalidDoubleQuote", { link = "NvimInvalidStringQuote" })
hl(0, "NvimInvalidDoubleQuotedBody", { link = "NvimInvalidStringBody" })
hl(0, "NvimInvalidDoubleQuotedEscape", { link = "NvimInvalidStringSpecial" })
hl(0, "NvimInvalidDoubleQuotedUnknownEscape", { link = "NvimInvalidValue" })
hl(0, "NvimInvalidEnvironmentName", { link = "NvimInvalidIdentifier" })
hl(0, "NvimInvalidEnvironmentSigil", { link = "NvimInvalidOptionSigil" })
hl(0, "NvimInvalidFigureBrace", { link = "NvimInvalidDelimiter" })
hl(0, "NvimInvalidFloat", { link = "NvimInvalidNumber" })
hl(0, "NvimInvalidIdentifier", { link = "NvimInvalidValue" })
hl(0, "NvimInvalidIdentifierKey", { link = "NvimInvalidIdentifier" })
hl(0, "NvimInvalidIdentifierName", { link = "NvimInvalidIdentifier" })
hl(0, "NvimInvalidIdentifierScope", { link = "NvimInvalidIdentifier" })
hl(0, "NvimInvalidIdentifierScopeDelimiter", { link = "NvimInvalidIdentifier" })
hl(0, "NvimInvalidLambda", { link = "NvimInvalidParenthesis" })
hl(0, "NvimInvalidList", { link = "NvimInvalidContainer" })
hl(0, "NvimInvalidMod", { link = "NvimInvalidBinaryOperator" })
hl(0, "NvimInvalidMultiplication", { link = "NvimInvalidBinaryOperator" })
hl(0, "NvimInvalidNestingParenthesis", { link = "NvimInvalidParenthesis" })
hl(0, "NvimInvalidNot", { link = "NvimInvalidUnaryOperator" })
hl(0, "NvimInvalidNumber", { link = "NvimInvalidValue" })
hl(0, "NvimInvalidNumberPrefix", { link = "NvimInvalidNumber" })
hl(0, "NvimInvalidOperator", { link = "NvimInvalid" })
hl(0, "NvimInvalidOptionName", { link = "NvimInvalidIdentifier" })
hl(0, "NvimInvalidOptionScope", { link = "NvimInvalidIdentifierScope" })
hl(0, "NvimInvalidOptionScopeDelimiter", { link = "NvimInvalidIdentifierScopeDelimiter" })
hl(0, "NvimInvalidOptionSigil", { link = "NvimInvalidIdentifier" })
hl(0, "NvimInvalidOr", { link = "NvimInvalidBinaryOperator" })
hl(0, "NvimInvalidParenthesis", { link = "NvimInvalidDelimiter" })
hl(0, "NvimInvalidPlainAssignment", { link = "NvimInvalidAssignment" })
hl(0, "NvimInvalidRegister", { link = "NvimInvalidValue" })
hl(0, "NvimInvalidSingleQuote", { link = "NvimInvalidStringQuote" })
hl(0, "NvimInvalidSingleQuotedBody", { link = "NvimInvalidStringBody" })
hl(0, "NvimInvalidSingleQuotedQuote", { link = "NvimInvalidStringSpecial" })
hl(0, "NvimInvalidSingleQuotedUnknownEscape", { link = "NvimInternalError" })
hl(0, "NvimInvalidSpacing", { link = "ErrorMsg" })
hl(0, "NvimInvalidString", { link = "NvimInvalidValue" })
hl(0, "NvimInvalidStringBody", { link = "NvimStringBody" })
hl(0, "NvimInvalidStringQuote", { link = "NvimInvalidString" })
hl(0, "NvimInvalidStringSpecial", { link = "NvimStringSpecial" })
hl(0, "NvimInvalidSubscript", { link = "NvimInvalidParenthesis" })
hl(0, "NvimInvalidSubscriptBracket", { link = "NvimInvalidSubscript" })
hl(0, "NvimInvalidSubscriptColon", { link = "NvimInvalidSubscript" })
hl(0, "NvimInvalidTernary", { link = "NvimInvalidOperator" })
hl(0, "NvimInvalidTernaryColon", { link = "NvimInvalidTernary" })
hl(0, "NvimInvalidUnaryMinus", { link = "NvimInvalidUnaryOperator" })
hl(0, "NvimInvalidUnaryOperator", { link = "NvimInvalidOperator" })
hl(0, "NvimInvalidUnaryPlus", { link = "NvimInvalidUnaryOperator" })
hl(0, "NvimInvalidValue", { link = "NvimInvalid" })
hl(0, "NvimLambda", { link = "NvimParenthesis" })
hl(0, "NvimList", { link = "NvimContainer" })
hl(0, "NvimMod", { link = "NvimBinaryOperator" })
hl(0, "NvimMultiplication", { link = "NvimBinaryOperator" })
hl(0, "NvimNestingParenthesis", { link = "NvimParenthesis" })
hl(0, "NvimNot", { link = "NvimUnaryOperator" })
hl(0, "NvimNumber", { link = "Number" })
hl(0, "NvimNumberPrefix", { link = "Type" })
hl(0, "NvimOperator", { link = "Operator" })
hl(0, "NvimOptionName", { link = "NvimIdentifier" })
hl(0, "NvimOptionScope", { link = "NvimIdentifierScope" })
hl(0, "NvimOptionScopeDelimiter", { link = "NvimIdentifierScopeDelimiter" })
hl(0, "NvimOptionSigil", { link = "Type" })
hl(0, "NvimOr", { link = "NvimBinaryOperator" })
hl(0, "NvimParenthesis", { link = "Delimiter" })
hl(0, "NvimPlainAssignment", { link = "NvimAssignment" })
hl(0, "NvimRegister", { link = "SpecialChar" })
hl(0, "NvimSingleQuote", { link = "NvimStringQuote" })
hl(0, "NvimSingleQuotedBody", { link = "NvimStringBody" })
hl(0, "NvimSingleQuotedQuote", { link = "NvimStringSpecial" })
hl(0, "NvimSingleQuotedUnknownEscape", { link = "NvimInternalError" })
hl(0, "NvimSpacing", { link = "Normal" })
hl(0, "NvimString", { link = "String" })
hl(0, "NvimStringBody", { link = "NvimString" })
hl(0, "NvimStringQuote", { link = "NvimString" })
hl(0, "NvimStringSpecial", { link = "SpecialChar" })
hl(0, "NvimSubscript", { link = "NvimParenthesis" })
hl(0, "NvimSubscriptBracket", { link = "NvimSubscript" })
hl(0, "NvimSubscriptColon", { link = "NvimSubscript" })
hl(0, "NvimTernary", { link = "NvimOperator" })
hl(0, "NvimTernaryColon", { link = "NvimTernary" })
hl(0, "NvimTreeBookmarkHL", { link = "SpellLocal" })
hl(0, "NvimTreeBookmarkIcon", { link = "NvimTreeFolderIcon" })
hl(0, "NvimTreeClosedFolderIcon", { link = "NvimTreeFolderIcon" })
hl(0, "NvimTreeCopiedHL", { link = "SpellRare" })
hl(0, "NvimTreeCursorColumn", { link = "CursorColumn" })
hl(0, "NvimTreeCursorLine", { link = "CursorLine" })
hl(0, "NvimTreeCursorLineNr", { link = "CursorLineNr" })
hl(0, "NvimTreeCutHL", { link = "SpellBad" })
hl(0, "NvimTreeDiagnosticErrorFileHL", { link = "DiagnosticUnderlineError" })
hl(0, "NvimTreeDiagnosticErrorFolderHL", { link = "NvimTreeDiagnosticErrorFileHL" })
hl(0, "NvimTreeDiagnosticErrorIcon", { link = "DiagnosticError" })
hl(0, "NvimTreeDiagnosticHintFileHL", { link = "DiagnosticUnderlineHint" })
hl(0, "NvimTreeDiagnosticHintFolderHL", { link = "NvimTreeDiagnosticHintFileHL" })
hl(0, "NvimTreeDiagnosticHintIcon", { link = "DiagnosticHint" })
hl(0, "NvimTreeDiagnosticInfoFileHL", { link = "DiagnosticUnderlineInfo" })
hl(0, "NvimTreeDiagnosticInfoFolderHL", { link = "NvimTreeDiagnosticInfoFileHL" })
hl(0, "NvimTreeDiagnosticInfoIcon", { link = "DiagnosticInfo" })
hl(0, "NvimTreeDiagnosticWarnFileHL", { link = "DiagnosticUnderlineWarn" })
hl(0, "NvimTreeDiagnosticWarnFolderHL", { link = "NvimTreeDiagnosticWarnFileHL" })
hl(0, "NvimTreeDiagnosticWarnIcon", { link = "DiagnosticWarn" })
hl(0, "NvimTreeEmptyFolderName", { link = "Directory" })
hl(0, "NvimTreeEndOfBuffer", { fg = "#1b1c1e", bg = "#1b1c1e" })
hl(0, "NvimTreeExecFile", { link = "Question" })
hl(0, "NvimTreeFileIcon", { link = "NvimTreeNormal" })
hl(0, "NvimTreeFolderArrowClosed", { link = "NvimTreeIndentMarker" })
hl(0, "NvimTreeFolderArrowOpen", { link = "NvimTreeIndentMarker" })
hl(0, "NvimTreeFolderIcon", { fg = "#8094b4" })
hl(0, "NvimTreeFolderName", { fg = "#57a5e5" })
hl(0, "NvimTreeGitDeleted", { fg = "#de5d68" })
hl(0, "NvimTreeGitDeletedIcon", { link = "Statement" })
hl(0, "NvimTreeGitDirty", { fg = "#dbb671" })
hl(0, "NvimTreeGitDirtyIcon", { link = "Statement" })
hl(0, "NvimTreeGitFileDeletedHL", { link = "NvimTreeGitDeletedIcon" })
hl(0, "NvimTreeGitFileDirtyHL", { link = "NvimTreeGitDirtyIcon" })
hl(0, "NvimTreeGitFileIgnoredHL", { link = "NvimTreeGitIgnoredIcon" })
hl(0, "NvimTreeGitFileMergeHL", { link = "NvimTreeGitMergeIcon" })
hl(0, "NvimTreeGitFileNewHL", { link = "NvimTreeGitNewIcon" })
hl(0, "NvimTreeGitFileRenamedHL", { link = "NvimTreeGitRenamedIcon" })
hl(0, "NvimTreeGitFileStagedHL", { link = "NvimTreeGitStagedIcon" })
hl(0, "NvimTreeGitFolderDeletedHL", { link = "NvimTreeGitFileDeletedHL" })
hl(0, "NvimTreeGitFolderDirtyHL", { link = "NvimTreeGitFileDirtyHL" })
hl(0, "NvimTreeGitFolderIgnoredHL", { link = "NvimTreeGitFileIgnoredHL" })
hl(0, "NvimTreeGitFolderMergeHL", { link = "NvimTreeGitFileMergeHL" })
hl(0, "NvimTreeGitFolderNewHL", { link = "NvimTreeGitFileNewHL" })
hl(0, "NvimTreeGitFolderRenamedHL", { link = "NvimTreeGitFileRenamedHL" })
hl(0, "NvimTreeGitFolderStagedHL", { link = "NvimTreeGitFileStagedHL" })
hl(0, "NvimTreeGitIgnoredIcon", { link = "Comment" })
hl(0, "NvimTreeGitMergeIcon", { link = "Constant" })
hl(0, "NvimTreeGitNew", { fg = "#8fb573" })
hl(0, "NvimTreeGitNewIcon", { link = "PreProc" })
hl(0, "NvimTreeGitRenamedIcon", { link = "PreProc" })
hl(0, "NvimTreeGitStagedIcon", { link = "Constant" })
hl(0, "NvimTreeHiddenDisplay", { link = "Conceal" })
hl(0, "NvimTreeHiddenFileHL", { link = "NvimTreeHiddenIcon" })
hl(0, "NvimTreeHiddenFolderHL", { link = "NvimTreeHiddenFileHL" })
hl(0, "NvimTreeHiddenIcon", { link = "Conceal" })
hl(0, "NvimTreeImageFile", { fg = "#79428a" })
hl(0, "NvimTreeIndentMarker", { fg = "#a7aab0" })
hl(0, "NvimTreeLineNr", { link = "LineNr" })
hl(0, "NvimTreeLiveFilterPrefix", { link = "PreProc" })
hl(0, "NvimTreeLiveFilterValue", { link = "ModeMsg" })
hl(0, "NvimTreeModifiedFileHL", { link = "NvimTreeModifiedIcon" })
hl(0, "NvimTreeModifiedFolderHL", { link = "NvimTreeModifiedFileHL" })
hl(0, "NvimTreeModifiedIcon", { link = "Type" })
hl(0, "NvimTreeNormal", { fg = "#a7aab0", bg = "#1b1c1e" })
hl(0, "NvimTreeNormalFloat", { fg = "#a7aab0", bg = "#1b1c1e" })
hl(0, "NvimTreeNormalFloatBorder", { link = "FloatBorder" })
hl(0, "NvimTreeNormalNC", { link = "NvimTreeNormal" })
hl(0, "NvimTreeOpenedFolderIcon", { link = "NvimTreeFolderIcon" })
hl(0, "NvimTreeOpenedFolderName", { link = "Directory" })
hl(0, "NvimTreeOpenedHL", { link = "Special" })
hl(0, "NvimTreePopup", { link = "Normal" })
hl(0, "NvimTreeRootFolder", { fg = "#c49060", bold = true })
hl(0, "NvimTreeSignColumn", { link = "NvimTreeNormal" })
hl(0, "NvimTreeSpecialFile", { fg = "#dbb671", underline = true })
hl(0, "NvimTreeStatusLine", { link = "StatusLine" })
hl(0, "NvimTreeStatusLineNC", { link = "StatusLineNC" })
hl(0, "NvimTreeSymlink", { fg = "#bb70d2" })
hl(0, "NvimTreeSymlinkFolderName", { link = "Directory" })
hl(0, "NvimTreeSymlinkIcon", { link = "NvimTreeNormal" })
hl(0, "NvimTreeVertSplit", { fg = "#1b1c1e", bg = "#1b1c1e" })
hl(0, "NvimTreeWinSeparator", { link = "WinSeparator" })
hl(0, "NvimTreeWindowPicker", { fg = "#ededed", bg = "#4493c8", bold = true })
hl(0, "NvimUnaryMinus", { link = "NvimUnaryOperator" })
hl(0, "NvimUnaryOperator", { link = "NvimOperator" })
hl(0, "NvimUnaryPlus", { link = "NvimUnaryOperator" })

-- Ok
hl(0, "OkMsg", { fg = "#b3f6c0" })

-- Operator
hl(0, "Operator", { fg = "#bb70d2" })

-- Pmenu
hl(0, "Pmenu", { fg = "#a7aab0", bg = "#2c2d31" })
hl(0, "PmenuBorder", { link = "Pmenu" })
hl(0, "PmenuExtra", { link = "Pmenu" })
hl(0, "PmenuExtraSel", { link = "PmenuSel" })
hl(0, "PmenuKind", { link = "Pmenu" })
hl(0, "PmenuKindSel", { link = "PmenuSel" })
hl(0, "PmenuMatch", { bold = true })
hl(0, "PmenuMatchSel", { bold = true })
hl(0, "PmenuSbar", { bg = "#2c2d31" })
hl(0, "PmenuSel", { fg = "#000000", bg = "#68aee8" })
hl(0, "PmenuShadow", { link = "FloatShadow" })
hl(0, "PmenuShadowThrough", { link = "FloatShadowThrough" })
hl(0, "PmenuThumb", { bg = "#5a5b5e" })

-- Pre
hl(0, "PreCondit", { fg = "#bb70d2" })
hl(0, "PreInsert", { link = "Added" })
hl(0, "PreProc", { fg = "#bb70d2" })

-- Question
hl(0, "Question", { fg = "#dbb671" })

-- Quick
hl(0, "QuickFixLine", { fg = "#57a5e5", underline = true })

-- Rainbow
hl(0, "RainbowBlue", { fg = "#57a5e5" })
hl(0, "RainbowCyan", { fg = "#51a8b3" })
hl(0, "RainbowDelimiterBlue", { fg = "#57a5e5" })
hl(0, "RainbowDelimiterCyan", { fg = "#51a8b3" })
hl(0, "RainbowDelimiterGreen", { fg = "#8fb573" })
hl(0, "RainbowDelimiterOrange", { fg = "#c49060" })
hl(0, "RainbowDelimiterRed", { fg = "#de5d68" })
hl(0, "RainbowDelimiterViolet", { fg = "#bb70d2" })
hl(0, "RainbowDelimiterYellow", { fg = "#dbb671" })
hl(0, "RainbowGreen", { fg = "#8fb573" })
hl(0, "RainbowOrange", { fg = "#c49060" })
hl(0, "RainbowRed", { fg = "#de5d68" })
hl(0, "RainbowViolet", { fg = "#bb70d2" })
hl(0, "RainbowYellow", { fg = "#dbb671" })

-- Redraw
hl(0, "RedrawDebugClear", { bg = "#6b5300" })
hl(0, "RedrawDebugComposed", { bg = "#005523" })
hl(0, "RedrawDebugNormal", { reverse = true })
hl(0, "RedrawDebugRecompose", { bg = "#590008" })

-- Removed
hl(0, "Removed", { fg = "#de5d68" })

-- Repeat
hl(0, "Repeat", { fg = "#bb70d2" })

-- Search
hl(0, "Search", { fg = "#000000", bg = "#e2c792" })

-- Sign
hl(0, "SignColumn", { fg = "#a7aab0", bg = "#000000" })

-- Snacks
hl(0, "SnacksDashboardDesc", { fg = "#51a8b3" })
hl(0, "SnacksDashboardFooter", { fg = "#833b3b", italic = true })
hl(0, "SnacksDashboardHeader", { fg = "#dbb671" })
hl(0, "SnacksDashboardIcon", { fg = "#51a8b3" })
hl(0, "SnacksDashboardKey", { fg = "#57a5e5" })
hl(0, "SnacksDashboardSpecial", { fg = "#833b3b", bold = true })
hl(0, "SnacksPicker", { fg = "#a7aab0", bg = "#000000" })
hl(0, "SnacksPickerBorder", { fg = "#51a8b3" })
hl(0, "SnacksPickerMatch", { fg = "#c49060", bold = true })
hl(0, "SnacksPickerTitle", { fg = "#de5d68" })

-- Snippet
hl(0, "SnippetTabstop", { link = "Visual" })
hl(0, "SnippetTabstopActive", { link = "SnippetTabstop" })

-- Special
hl(0, "Special", { fg = "#de5d68" })
hl(0, "SpecialChar", { fg = "#de5d68" })
hl(0, "SpecialComment", { fg = "#5a5b5e", italic = true })
hl(0, "SpecialKey", { fg = "#5a5b5e" })

-- Spell
hl(0, "SpellBad", { sp = "#de5d68", undercurl = true })
hl(0, "SpellCap", { sp = "#dbb671", undercurl = true })
hl(0, "SpellLocal", { sp = "#57a5e5", undercurl = true })
hl(0, "SpellRare", { sp = "#bb70d2", undercurl = true })

-- Statement
hl(0, "Statement", { fg = "#bb70d2" })

-- Status
hl(0, "StatusLine", { fg = "#a7aab0", bg = "#35363b" })
hl(0, "StatusLineCommandMode", { fg = "#1e2430", bg = "#a3be8c" })
hl(0, "StatusLineCommandModeSep", { fg = "#a3be8c", bg = "#a3be8c" })
hl(0, "StatusLineConfirmMode", { fg = "#1e2430", bg = "#5e81ac" })
hl(0, "StatusLineConfirmModeSep", { fg = "#5e81ac", bg = "#5e81ac" })
hl(0, "StatusLineCursor", { fg = "#a3be8c", bg = "#1e2430", bold = true })
hl(0, "StatusLineCursorIcon", { fg = "#1e2430", bg = "#a3be8c", bold = true })
hl(0, "StatusLineCursorSep", { fg = "#a3be8c", bg = "#1e2430", bold = true })
hl(0, "StatusLineCwd", { fg = "#aaaaaa", bg = "#1e2430", bold = true })
hl(0, "StatusLineCwdIcon", { fg = "#1e2430", bg = "#e06c75", bold = true })
hl(0, "StatusLineCwdSep", { fg = "#e06c75", bg = "#1e2430", bold = true })
hl(0, "StatusLineEmptySpace", { fg = "#1e2430", bg = "#1e2430", bold = true })
hl(0, "StatusLineFile", { fg = "#aaaaaa", bg = "#202020", bold = true })
hl(0, "StatusLineFileSep", { fg = "#202020", bg = "#1e2430", bold = true })
hl(0, "StatusLineGit", { fg = "#aaaaaa", bg = "#1e2430", bold = true })
hl(0, "StatusLineInsertMode", { fg = "#1e2430", bg = "#b48ead" })
hl(0, "StatusLineInsertModeSep", { fg = "#b48ead", bg = "#b48ead" })
hl(0, "StatusLineMode", { fg = "#ff9e64", bg = "#1f2335", bold = true })
hl(0, "StatusLineModeSep", { fg = "#1f2335", bg = "#1f2335", bold = true })
hl(0, "StatusLineNC", { fg = "#5a5b5e", bg = "#2c2d31" })
hl(0, "StatusLineNTerminalMode", { fg = "#1e2430", bg = "#ebcb8b" })
hl(0, "StatusLineNTerminalModeSep", { fg = "#ebcb8b", bg = "#ebcb8b" })
hl(0, "StatusLineNormalMode", { fg = "#1e2430", bg = "#81a1c1" })
hl(0, "StatusLineNormalModeSep", { fg = "#81a1c1", bg = "#81a1c1" })
hl(0, "StatusLineReplaceMode", { fg = "#1e2430", bg = "#88c0d0" })
hl(0, "StatusLineReplaceModeSep", { fg = "#88c0d0", bg = "#88c0d0" })
hl(0, "StatusLineSelectMode", { fg = "#1e2430", bg = "#5e81ac" })
hl(0, "StatusLineSelectModeSep", { fg = "#5e81ac", bg = "#5e81ac" })
hl(0, "StatusLineTerm", { fg = "#a7aab0", bg = "#35363b" })
hl(0, "StatusLineTermNC", { fg = "#5a5b5e", bg = "#2c2d31" })
hl(0, "StatusLineTerminalMode", { fg = "#1e2430", bg = "#a3be8c" })
hl(0, "StatusLineTerminalModeSep", { fg = "#a3be8c", bg = "#a3be8c" })
hl(0, "StatusLineVisualMode", { fg = "#1e2430", bg = "#d08770" })
hl(0, "StatusLineVisualModeSep", { fg = "#d08770", bg = "#d08770" })

-- Stderr
hl(0, "StderrMsg", { link = "ErrorMsg" })

-- Stdout

-- Storage
hl(0, "StorageClass", { fg = "#dbb671" })

-- String
hl(0, "String", { fg = "#8fb573" })

-- Structure
hl(0, "Structure", { fg = "#dbb671" })

-- Substitute
hl(0, "Substitute", { fg = "#000000", bg = "#8fb573" })

-- Other
hl(0, "TSRainbowBlue", { fg = "#57a5e5" })
hl(0, "TSRainbowCyan", { fg = "#51a8b3" })
hl(0, "TSRainbowGreen", { fg = "#8fb573" })
hl(0, "TSRainbowOrange", { fg = "#c49060" })
hl(0, "TSRainbowRed", { fg = "#de5d68" })
hl(0, "TSRainbowViolet", { fg = "#bb70d2" })
hl(0, "TSRainbowYellow", { fg = "#dbb671" })

-- Tab
hl(0, "TabLine", { fg = "#a7aab0", bg = "#2c2d31" })
hl(0, "TabLineFill", { fg = "#5a5b5e", bg = "#2c2d31" })
hl(0, "TabLineSel", { fg = "#000000", bg = "#a7aab0" })

-- Tag
hl(0, "Tag", { fg = "#8fb573" })

-- Telescope
hl(0, "TelescopeBorder", { fg = "#de5d68" })
hl(0, "TelescopeMatching", { fg = "#c49060", bold = true })
hl(0, "TelescopePreviewBorder", { fg = "#51a8b3" })
hl(0, "TelescopePromptBorder", { fg = "#51a8b3" })
hl(0, "TelescopePromptPrefix", { fg = "#8fb573" })
hl(0, "TelescopeResultsBorder", { fg = "#51a8b3" })
hl(0, "TelescopeSelection", { bg = "#35363b" })
hl(0, "TelescopeSelectionCaret", { fg = "#dbb671" })

-- Term
hl(0, "TermCursor", { reverse = true })

-- Terminal
hl(0, "Terminal", { fg = "#a7aab0", bg = "#000000" })

-- Title
hl(0, "Title", { fg = "#51a8b3" })

-- Todo
hl(0, "Todo", { fg = "#de5d68", italic = true })

-- Toolbar
hl(0, "ToolbarButton", { fg = "#000000", bg = "#68aee8" })
hl(0, "ToolbarLine", { fg = "#a7aab0" })

-- Type
hl(0, "Type", { fg = "#dbb671" })

-- Typedef
hl(0, "Typedef", { fg = "#dbb671" })

-- Underlined
hl(0, "Underlined", { underline = true })

-- Vert
hl(0, "VertSplit", { link = "WinSeparator" })

-- Visual
hl(0, "Visual", { bg = "#37383d" })
hl(0, "VisualNOS", { bg = "#35363b", underline = true })

-- Warning
hl(0, "WarningMsg", { fg = "#dbb671", bold = true })

-- Which
hl(0, "WhichKey", { fg = "#de5d68" })
hl(0, "WhichKeyDesc", { fg = "#57a5e5" })
hl(0, "WhichKeyGroup", { fg = "#c49060" })
hl(0, "WhichKeySeparator", { fg = "#8fb573" })

-- Whitespace
hl(0, "Whitespace", { fg = "#5a5b5e" })

-- Wild
hl(0, "WildMenu", { fg = "#000000", bg = "#57a5e5" })

-- Win
hl(0, "WinBar", { fg = "#a7aab0", bg = "#000000" })
hl(0, "WinBarNC", { fg = "#5a5b5e", bg = "#000000" })
hl(0, "WinSeparator", { fg = "#37383d" })

-- Other
hl(0, "cDefine", { fg = "#51a8b3" })
hl(0, "cInclude", { fg = "#57a5e5" })
hl(0, "cStorageClass", { fg = "#bb70d2" })
hl(0, "cTSConstMacro", { fg = "#bb70d2" })
hl(0, "cTSConstant", { fg = "#51a8b3" })
hl(0, "cTSInclude", { fg = "#57a5e5" })
hl(0, "cTSOperator", { fg = "#bb70d2" })
hl(0, "cTypedef", { fg = "#bb70d2" })
hl(0, "cppStatement", { fg = "#bb70d2", bold = true })
hl(0, "cppTSConstMacro", { fg = "#bb70d2" })
hl(0, "cppTSConstant", { fg = "#51a8b3" })
hl(0, "cppTSInclude", { fg = "#57a5e5" })
hl(0, "cppTSOperator", { fg = "#bb70d2" })
hl(0, "debugBreakpoint", { fg = "#000000", bg = "#de5d68" })
hl(0, "debugPC", { fg = "#000000", bg = "#8fb573" })
hl(0, "iCursor", { reverse = true })
hl(0, "illuminatedCurWord", { bg = "#35363b", bold = true })
hl(0, "illuminatedWord", { bg = "#35363b", bold = true })
hl(0, "lCursor", { reverse = true })
hl(0, "latexTSEnvironment", { fg = "#51a8b3", bold = true })
hl(0, "latexTSEnvironmentName", { fg = "#dbb671" })
hl(0, "latexTSFuncMacro", { fg = "#a7aab0" })
hl(0, "latexTSInclude", { fg = "#57a5e5" })
hl(0, "latexTSMath", { fg = "#c49060" })
hl(0, "latexTSTitle", { fg = "#8fb573" })
hl(0, "latexTSType", { fg = "#57a5e5" })
hl(0, "markdownBlockquote", { fg = "#5a5b5e" })
hl(0, "markdownBold", { bold = true })
hl(0, "markdownBoldDelimiter", { fg = "#5a5b5e" })
hl(0, "markdownCode", { fg = "#8fb573" })
hl(0, "markdownCodeBlock", { fg = "#8fb573" })
hl(0, "markdownCodeDelimiter", { fg = "#dbb671" })
hl(0, "markdownH1", { fg = "#de5d68", bold = true })
hl(0, "markdownH2", { fg = "#bb70d2", bold = true })
hl(0, "markdownH3", { fg = "#c49060", bold = true })
hl(0, "markdownH4", { fg = "#de5d68", bold = true })
hl(0, "markdownH5", { fg = "#bb70d2", bold = true })
hl(0, "markdownH6", { fg = "#c49060", bold = true })
hl(0, "markdownHeadingDelimiter", { fg = "#5a5b5e" })
hl(0, "markdownHeadingRule", { fg = "#5a5b5e" })
hl(0, "markdownId", { fg = "#dbb671" })
hl(0, "markdownIdDeclaration", { fg = "#de5d68" })
hl(0, "markdownItalic", { italic = true })
hl(0, "markdownItalicDelimiter", { fg = "#5a5b5e", italic = true })
hl(0, "markdownLinkDelimiter", { fg = "#5a5b5e" })
hl(0, "markdownLinkText", { fg = "#de5d68" })
hl(0, "markdownLinkTextDelimiter", { fg = "#5a5b5e" })
hl(0, "markdownListMarker", { fg = "#de5d68" })
hl(0, "markdownOrderedListMarker", { fg = "#de5d68" })
hl(0, "markdownRule", { fg = "#bb70d2" })
hl(0, "markdownUrl", { fg = "#57a5e5", underline = true })
hl(0, "markdownUrlDelimiter", { fg = "#5a5b5e" })
hl(0, "markdownUrlTitleDelimiter", { fg = "#8fb573" })
hl(0, "phpBoolean", { fg = "#51a8b3" })
hl(0, "phpFCKeyword", { fg = "#bb70d2" })
hl(0, "phpFunctions", { fg = "#a7aab0" })
hl(0, "phpHereDoc", { fg = "#8fb573" })
hl(0, "phpIdentifier", { fg = "#c49060" })
hl(0, "phpMemberSelector", { fg = "#a7aab0" })
hl(0, "phpMethods", { fg = "#51a8b3" })
hl(0, "phpNowDoc", { fg = "#8fb573" })
hl(0, "phpNumber", { fg = "#c49060" })
hl(0, "phpOperator", { fg = "#bb70d2" })
hl(0, "phpRegion", { fg = "#57a5e5" })
hl(0, "phpSCKeyword", { fg = "#bb70d2" })
hl(0, "phpStructure", { fg = "#bb70d2" })
hl(0, "phpVarSelector", { fg = "#c49060" })
hl(0, "rainbowcol1", { fg = "#818387" })
hl(0, "rainbowcol2", { fg = "#dbb671" })
hl(0, "rainbowcol3", { fg = "#57a5e5" })
hl(0, "rainbowcol4", { fg = "#c49060" })
hl(0, "rainbowcol5", { fg = "#bb70d2" })
hl(0, "rainbowcol6", { fg = "#8fb573" })
hl(0, "rainbowcol7", { fg = "#de5d68" })
hl(0, "scalaInterpolation", { fg = "#bb70d2" })
hl(0, "scalaInterpolationBoundary", { fg = "#bb70d2" })
hl(0, "scalaKeywordModifier", { fg = "#de5d68" })
hl(0, "scalaNameDefinition", { fg = "#a7aab0" })
hl(0, "scalaOperator", { fg = "#de5d68" })
hl(0, "scalaTypeOperator", { fg = "#de5d68" })
hl(0, "texCmd", { fg = "#bb70d2" })
hl(0, "texCmdEnv", { fg = "#51a8b3" })
hl(0, "texCmdPackage", { fg = "#57a5e5" })
hl(0, "texCmdPart", { fg = "#57a5e5" })
hl(0, "texEnvArgName", { fg = "#dbb671" })
hl(0, "texMathDelim", { fg = "#bb70d2" })
hl(0, "texMathDelimZone", { fg = "#818387" })
hl(0, "texMathOper", { fg = "#de5d68" })
hl(0, "texMathZoneX", { fg = "#c49060" })
hl(0, "texMathZoneXX", { fg = "#c49060" })
hl(0, "texPgfType", { fg = "#dbb671" })
hl(0, "vCursor", { reverse = true })
hl(0, "vimCommentTitle", { fg = "#818387", italic = true })
hl(0, "vimMap", { fg = "#bb70d2" })
hl(0, "vimMapLhs", { fg = "#a7aab0" })
hl(0, "vimMapModKey", { fg = "#c49060" })
hl(0, "vimMapRhs", { fg = "#57a5e5" })
hl(0, "vimNotation", { fg = "#de5d68" })
hl(0, "vimOption", { fg = "#de5d68" })
hl(0, "vimSetEqual", { fg = "#dbb671" })
hl(0, "vimVar", { fg = "#a7aab0" })
